version: '3.4'
services:
  exchange_zookeeper:
    image: zookeeper
    container_name: exchange_zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - ./volumes/exchange_zookeeper/log:/var/log/zookeeper

  exchange_kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: exchange_kafka
    restart: always
    logging:
      options:
        max-size: 10m
    ports:
      - "9092:9092"
    volumes:
      - ./volumes/exchange_kafka/log:/var/log/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "trades:1:1,orders:1:1,balances:1:1,internaltransfer:1:1,registeruser:1:1,unifyevents:1:1"

  exchange_envoy:
    image: envoyproxy/envoy-dev:f2906f5ce372814b8e6f688a0e1766703d8b56f2
    container_name: exchange_envoy
    restart: always
    ports:
      - "8765:8765"
    command: -c /etc/envoy/envoy.yaml --log-level debug
    volumes:
      - ./envoy_config/exchange.yaml:/etc/envoy/envoy.yaml
      - ./proto_config/exchange_matchengine.pb:/tmp/envoy/proto.pb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rollup_enovy:
    image: envoyproxy/envoy-dev:f2906f5ce372814b8e6f688a0e1766703d8b56f2
    container_name: rollup_enovy
    restart: always
    ports:
      - "8766:8765"
    command: -c /etc/envoy/envoy.yaml --log-level debug
    volumes:
      - ./envoy_config/rollup.yaml:/etc/envoy/envoy.yaml
      - ./proto_config/rollup_state.pb:/tmp/envoy/proto.pb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  exchange_db:
    image: timescale/timescaledb:2.1.0-pg13
    container_name: exchange_db
    restart: always
    volumes:
      - ./volumes/exchange_db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: exchange
      POSTGRES_PASSWORD: exchange_AA9944

  rollup_db:
    image: timescale/timescaledb:2.1.0-pg13
    container_name: rollup_db
    restart: always
    volumes:
      - ./volumes/rollup_db/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: rollup
      POSTGRES_USER: rollup
      POSTGRES_PASSWORD: rollup_AA9944
